apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: dev                 # skaffold 실행시 -p로 정의된 profile
    build:
      local:
        push: true # false는 로컬 테스트
      artifacts:
        - image: docker.io/rla8127/demo-scg # on dev server (docker hub에 push하고 실행)
          # - image: demo-scg   # local(로컬/push없이 실행만)
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"  # jib 플러그인을 통해 dev profile에 대해 수행
            fromImage: docker.io/library/openjdk:11.0.11-jre              # 실행을 위한 runtime image
    deploy:
      kustomize:
        paths:
          - k8s/base
